name: Lint merge commit nameeeee

on:
  pull_request:
    types: [ "opened", "synchronize" ]
    branches: [ "master" ]
  merge_group:

jobs:
  lint-commit-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Debug - Show event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          
      - name: Debug - Show commit message
        run: git log -1 --pretty=%B
          
      - uses: wagoid/commitlint-github-action@v6
        with:
          commitDepth: 3
