name: Lint merge commit name

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  lint-commit-name:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
        with:
          commitDepth: 1
  
