name: Lint merge commit name

on:
  pull_request:
    types: [synchronize, edited]
  merge_group:

jobs:
  lint-commit-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Show commit message
        run: git log -1 --pretty=%B
      - uses: wagoid/commitlint-github-action@v5
  
